name: Deploy Backend to Cloud Run

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t asia-south1-docker.pkg.dev/trusty-solution-463105-a1/air-quality-repo/backend ./backend
        docker push asia-south1-docker.pkg.dev/trusty-solution-463105-a1/air-quality-repo/backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy air-quality-backend \
          --image=asia-south1-docker.pkg.dev/trusty-solution-463105-a1/air-quality-repo/backend \
          --platform=managed \
          --region=asia-south1 \
          --allow-unauthenticated \
          --project=trusty-solution-463105-a1

