name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'air_quality_web/**'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'

    - name: Install Flutter dependencies
      working-directory: air_quality_web
      run: flutter pub get

    - name: Build Flutter web
      working-directory: air_quality_web
      run: flutter build web

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and push Docker image
      run: |
        docker build -t asia-south1-docker.pkg.dev/trusty-solution-463105-a1/air-quality-repo/frontend ./air_quality_web
        docker push asia-south1-docker.pkg.dev/trusty-solution-463105-a1/air-quality-repo/frontend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy air-quality-frontend \
          --image=asia-south1-docker.pkg.dev/trusty-solution-463105-a1/air-quality-repo/frontend \
          --platform=managed \
          --region=asia-south1 \
          --allow-unauthenticated
